# Generated by Django 4.0.4 on 2022-04-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, verbose_name='Data de criação')),
                ('valor', models.BooleanField()),
                ('validade', models.DateTimeField()),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
            ],
            options={
                'db_table': 'cadastramento',
            },
        ),
    ]
